spring:
  application:
    name: finanzas-app
  datasource:
    url: jdbc:postgresql://localhost:5432/fintechBD
    username: orionadmin
    password: Contrasenia123-
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      write-dates-as-timestamps: false
server:
  port: 8080
